
#ifndef POLYGATOR_TOOLS_H
#define POLYGATOR_TOOLS_H

#define POLYGATOR_SUBSYSTEM_FILE_PATH "/dev/polygator/subsystem"

enum {
    RADIO_MODULE_STATE_FAILED = -1,
    RADIO_MODULE_STATE_INIT = 0,
    RADIO_MODULE_STATE_CHECK_STATUS = 1,
    RADIO_MODULE_STATE_ENABLED = 2,
    RADIO_MODULE_STATE_HOLD_KEY = 3,
    RADIO_MODULE_STATE_CHECK_POWER_SUPPLY = 4,
    RADIO_MODULE_STATE_HOLD_POWER_SUPPLY = 5,
    RADIO_MODULE_STATE_DISABLED = 6,
};

#endif // POLYGATOR_TOOLS_H
