/* ss_status.h */

#ifndef __SS_STATUS_H__
#define __SS_STATUS_H__

#define RESPONSE_WRONG_HEADER_CHECKSUM		1
#define RESPONSE_WRONG_PROTOCOL_NAME		2
#define RESPONSE_WRONG_DATA_CHECKSUM		3
#define RESPONSE_WRONG_LOGIN				4
#define RESPONSE_WRONG_PASSWORD				5
#define RESPONSE_WRONG_AUTH					6
#define RESPONSE_WRONG_UID					7
#define RESPONSE_WRONG_IP					8
#define RESPONSE_EXPIRED					9
#define RESPONSE_WRONG_DATA					10
#define RESPONSE_FAILED_TOREAD_FILENAME		11
#define RESPONSE_WRONG_FILENAME				12
#define RESPONSE_GATE_BUZY					13
#define RESPONSE_GATE_NOTSUPPORTED			14
#define RESPONSE_WRONG_SESSION_ID			15
#define RESPONSE_WRONG_ATR					16
#define RESPONSE_WRONG_CHANNEL				0x40
#define RESPONSE_WRONG_VERSION				0xfe
#define RESPONSE_UNKOWN_ERROR				0xff

#endif //__SS_STATUS_H__
